### ISSUE TITLE
System Time GNSS issue

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/hdc_firmware#218]

**Comment by jayalberts** [comment]
shouldn't approve test data? potentially mismatches

**Comment by Masaya-RT** [comment]
Issue is fixed in 4.2.5 - No bad mismatches between GNSS + System time
- Cool: even without processed GNSS message, it will eventually catch up
- Cannot do this for frames. Busy System = permanently missed frames = trail hole
Following up with @mazar-farran to overcome this issue. Last step in improvement

**Comment by Masaya-RT** [comment]
Solved in 4.2.7
